function 정보 () {
    strip.show()
    strip.setPixelColor(59, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(38, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(39, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(70, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(71, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(87, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(75, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(54, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(73, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(86, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(42, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(53, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(74, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(85, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(43, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(167, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(184, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(199, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(168, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(183, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(200, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(169, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(182, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(201, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(136, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(149, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(180, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(213, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(232, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
}
function 눔감기_오렌지 () {
    strip.show()
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(69, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(90, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(101, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(154, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(197, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(40, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(215, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(214, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(232, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(233, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(75, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(84, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(107, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(116, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(139, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(148, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(171, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(180, neopixel.colors(NeoPixelColors.White))
    strip.show()
}
function 새싹활짝 () {
    strip.show()
    strip.setPixelColor(118, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(137, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(116, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(139, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(115, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(140, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(117, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(138, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(34, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(35, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(60, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(36, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(59, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(68, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(91, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(69, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(90, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(101, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(70, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(89, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(102, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(121, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(134, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(153, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(166, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(164, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(185, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(103, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(120, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(135, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(152, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(221, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(195, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(220, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(154, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(187, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(196, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(219, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(154, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(196, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(219, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(197, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(152, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(119, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(136, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(134, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(46, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(49, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(78, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(81, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(110, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(113, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(142, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(145, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(174, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(177, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(206, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(209, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(47, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(48, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(79, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(80, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(111, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(112, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(143, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(144, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(175, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(176, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(207, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(208, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(114, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(141, neopixel.colors(NeoPixelColors.Green))
    strip.show()
}
function 별로 () {
    strip.show()
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(69, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(90, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(101, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(154, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(197, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(40, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(215, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(214, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(232, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(233, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(74, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(86, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(105, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(118, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(137, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(150, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(169, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(181, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(203, neopixel.colors(NeoPixelColors.White))
    strip.show()
}
function 윙크 () {
    strip.show()
    strip.setPixelColor(67, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(91, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(101, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(89, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(71, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(163, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(164, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(166, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(167, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(188, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(187, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(185, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(184, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(42, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(76, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(82, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(109, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(114, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(141, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(146, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(173, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(179, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(213, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(214, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(234, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(233, neopixel.colors(NeoPixelColors.Green))
    strip.show()
}
input.onButtonPressed(Button.A, function () {
	
})
function 정보깜박 () {
    strip.show()
    strip.setPixelColor(59, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(38, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(39, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(70, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(71, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(87, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(75, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(54, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(73, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(86, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(42, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(53, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(74, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(85, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(43, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(167, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(184, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(199, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(168, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(183, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(200, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(169, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(182, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(201, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(136, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(149, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(180, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(213, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(232, neopixel.colors(NeoPixelColors.Orange))
    strip.show()
}
function 기쁨 () {
    strip.show()
    strip.setPixelColor(67, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(92, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(68, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(91, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(69, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(90, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(89, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(71, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(88, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(70, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(163, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(164, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(166, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(167, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(188, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(187, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(185, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(184, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(42, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(76, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(82, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(109, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(114, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(141, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(146, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(173, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(179, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(213, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(214, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(234, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(233, neopixel.colors(NeoPixelColors.Green))
    strip.show()
}
function 눈물 () {
    strip.show()
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(69, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(90, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(101, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(154, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(197, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(40, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(215, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(214, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(232, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(233, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(74, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(86, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(105, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(118, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(137, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(150, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(169, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(181, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(203, neopixel.colors(NeoPixelColors.White))
    strip.show()
}
function 새싹중간 () {
    strip.show()
    strip.setPixelColor(38, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(39, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(56, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(55, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(72, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(87, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(73, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(86, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(105, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(118, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(137, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(200, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(150, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(169, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(182, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(168, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(183, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(199, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(116, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(139, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(115, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(140, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(106, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(117, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(138, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(149, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(216, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(217, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(45, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(50, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(77, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(82, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(109, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(114, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(141, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(146, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(173, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(205, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(210, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(46, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(49, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(78, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(81, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(110, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(113, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(142, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(145, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(174, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(177, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(206, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(209, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(48, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(79, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(80, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(111, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(112, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(143, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(144, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(175, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(176, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(207, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    strip.setPixelColor(178, neopixel.colors(NeoPixelColors.Red))
}
function 새싹 () {
    strip.show()
    strip.setPixelColor(70, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(89, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(88, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(103, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(104, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(120, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(119, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(135, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(136, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(152, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(151, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(166, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(167, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(185, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(118, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(137, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(117, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(138, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(43, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(52, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(75, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(84, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(107, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(116, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(139, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(148, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(171, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(180, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(203, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(212, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(44, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(51, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(76, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(83, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(108, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(115, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(140, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(147, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(172, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(179, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(204, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(211, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(50, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(77, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(82, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(109, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(114, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(141, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(146, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(173, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(178, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(205, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(49, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(78, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(81, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(110, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(113, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(142, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(145, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(174, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(177, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(206, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(48, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(79, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(80, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(111, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(112, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(143, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(144, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(175, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(176, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(207, neopixel.colors(NeoPixelColors.Red))
    strip.show()
}
function 눔감기초록 () {
    strip.show()
    strip.setPixelColor(58, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(69, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(90, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(101, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(154, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(165, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(186, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(197, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(40, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(41, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(215, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(214, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(232, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(233, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(75, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(84, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(107, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(116, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(139, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(148, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(171, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(180, neopixel.colors(NeoPixelColors.White))
    strip.show()
}
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P13, 256, NeoPixelMode.RGB)
basic.forever(function () {
    기쁨()
})
